### ISSUE TITLE
error in the README due to a numpy update

### ISSUE THREAD

**Issue by tmcclintock** [rmcgibbo/pyhmc#13]
In the readme and the docs, the number of samples specified in the simple example is written as `n_samples=1e4`. With a recent numpy update (not sure which) it won't automatically convert a float to an int when you get to the line in `hmc.py`: `samples = np.zeros((n_samples, n_params))`. Thus, you get an error if you run the sample script as-is. If you change it it to `n_samples=10000` it works fine.

**Comment by rmcgibbo** [comment]
Fixed.
