### ISSUE TITLE
The 0.5 scale in the leapfrog method in hmc_main_loop in _hmc.pyx

### ISSUE THREAD

**Issue by xuhuifan** [rmcgibbo/pyhmc#16]
Hi Robert, 

I found that in line 109 of the _hmc.pyx, there is an additional 0.5 scale in updating p (the full ), while as in standard HMC method (Neal's MCMC using Hamiltonian dynamics) there is no such term. May I ask if I have mis-understood anything?

Thanks, 
Xuhui

**Comment by rmcgibbo** [comment]
sorry, i don't have the band with to track it down. i think you can find that term if you follow back the chain of ownership of this project, e.g. to the python and matlab functions in https://github.com/koepsell/pyhmc. best of luck.

**Comment by xuhuifan** [comment]
Thanks, Robert. This is what I was concerned. In you link, both of the hmc2.m and hmc2.py do not contain the 0.5 scale factor. 
Please see line 357 of https://github.com/koepsell/pyhmc/blob/master/hmc2.py
and line 199 of https://github.com/koepsell/pyhmc/blob/master/hmc2.m

Xuhui

**Comment by rmcgibbo** [comment]
Got it. How about you fix it with a pull request?

**Comment by xuhuifan** [comment]
Great. Pushing a PR now. 
Thanks,
